EarthAsteroidWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('simulation/', include(("simulation.urls", "simulation"), namespace="simulation")),
    path('', include(("asteroidInfo.urls", "asteroidInfo"), namespace="asteroidInfo"))
]

asteroidInfo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

simulation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

asteroidInfo/models.py
from django.db import models

# Create your models here.

simulation/models.py
from django.db import models

# Create your models here.

asteroidInfo/views.py
from django.http import HttpResponse
from django.shortcuts import render

  # Create your views here.
def index(request):
    return render(request, "asteroidInfo/index.html")

simulation/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "simulation/index.html")

asteroidInfo/templates/asteroidInfo/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        
        <script src=
        "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
          <script
            src=
        "https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
            type="text/javascript"
          ></script>
          <script src=
        "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
          <script src=
        "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.min.js"></script>
    <style>
        body {
            font-family: "Verdana";
        }
        #topBtn {
            display: none;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            border: none;
            outline: none;
            background-color: grey;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 200px;
        }

        #topBtn:hover {
            background-color: #555;
        }
    </style>
    <body class="text-center">
        <button onclick="topFunction()" id="topBtn" title="Go to top"><span data-feather="arrow-up"></span></button>
        <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
            <a class="navbar-brand" href="#">Earth Asteroid Web</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="#">Info</a>
                    <a class="nav-item nav-link" href="#">Classes</a>
                    <a class="nav-item nav-link" href="{% url 'simulation:index' %}">Simulation</a>
                    <a class="nav-item nav-link" href="#">Calculator</a>
                </div>
            </div>
        </nav>
        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column", style="background-image: url('https://images.newscientist.com/wp-content/uploads/2021/08/20165006/PRI_195542462.jpg'); height: 100%">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                <h1 class="display-3">Earth Asteroid Web</h1>
                <p class="lead">A warning: we are getting trapped...</p>
                </div>
            </div>
        </div>
        <br>
        <div class="shadow container">
            <div class="row">
                <div class="col align-self-center">
                    <h1>What do you mean?</h1>
                    <p>Surrounding the Earth, there exists a large group of asteroids that orbit the Earth... very closely. Some of these
                        are made of rocks, but the truth is, most of them are man-made, or more specifically, the waste that rockets dispose of when 
                        they exit the atmosphere of the Earth. As of November 4, 2021, 27,323 near-Earth asteroids are known, 2,224 of which are 
                        both sufficiently large and come sufficiently close to Earth to be considered potentially hazardous, and these asteroids 
                        will last for millions of years.
                    </p>
                </div>
            </div>
        </div><br><br>
        <div class="container">
            <div class="row">
                <div class="col-lg-4 align-self-center">
                    <h1>Orbital Periods</h1>
                    <p>These asteroids can take centuries to orbit depending on the height of orbit. Others will fall back to Earth within
                        several years. Some are in between and just float around.
                    </p>
                </div>
                <div class="col-lg-4 align-self-center">
                    <h1>Orbital Speeds</h1>
                    <p>They travel at speeds up to 17,500 mph, fast enough for a relatively small piece of orbital debris to damage a 
                        satellite or a spacecraft. here are approximately 100 million pieces of debris about .04 inches (or one millimeter) 
                        and larger.
                    </p>
                </div>
                <div class="col-lg-4 align-self-center">
                    <h1>Tracking Debris</h1>
                    <p>The Department of Defense and NASA maintains a highly accurate satellite catalog on objects in Earth orbit. Most of 
                        the cataloged objects are larger than a softball (approximately 10 centimeters).
                    </p>
                </div>
            </div><br>
            <canvas class="my-4 w-100" id="lineChart"></canvas><br>
            <canvas class="my-4 w-100" id="lineChart2"></canvas><br>
            <div class="row align-items-center">
                <div class="col-lg">
                    <h1>Facts and Figures</h1>
                    <p>The amount of debris that orbits the Earth has been increasing exponentially since the first space debris was discovered
                        in 1959. Also, a lot of this debris isn't even functional spacecraft - it's mainly the parts that rockets dispatch and 
                        excess rocket fuel. Learn more by navigating to the Info page. Note that the above stats are only estimates.
                    </p>
                </div>
            </div>
        </div><br>
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="container-fluid text-center text-md-left">
                <div class="row">
                    <div class="col-md-6 mt-md-0 mt-3">
                        <h5 class="text-uppercase">Citations and Sources</h5>
                        <p>Remember: this content wasn't taken of the top of someone's head. It is the result of the hardwork put
                            into a documentation by NASA and other space agencies. Here are the links to the other sources that were
                            used as data.
                        </p>
                    </div>
                    <div class="col-md-3 mb-md-0 mb-3">
                        <h5 class="text-uppercase">Links</h5>
                        <ul class="list-unstyled text-small">
                            <li><a href="https://www.nasa.gov/mission_pages/station/news/orbital_debris.html" target="_blank" class="text-muted">NASA</a></li>
                            <li><a href="https://www.statista.com/chart/24980/space-debris-in-orbit/" target="_blank" class="text-muted">Statista</a></li>
                            <li><a href="https://www.space-track.org/documentation" target="_blank" class="text-muted">USSpaceCom</a></li>
                            <li><a href="http://astria.tacc.utexas.edu/AstriaGraph/" target="_blank" class="text-muted">Astria Graph</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="footer-copyright text-center py-3" style="background-color: rgb(192, 192, 192);">Created by Jeff John Sunil</div>
        </footer>
    </body>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.7.1/dist/Chart.min.js"></script>
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
    <script>
        data1 = [0, 200, 700, 1750, 2500, 3000, 7000];
        data2 = [0, 1500, 4000, 6000, 9500, 16000, 23500];
        for (var x = 0; x < data1.length; x++) {
            data2[x] -= data1[x]
        }
        var ctx = document.getElementById("lineChart").getContext('2d');
        var ctx2 = document.getElementById("lineChart2").getContext('2d');
        var myLineChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ["1960", "1970", "1980", "1990", "2000", "2010", "2020"],
            datasets: [
                {
                    label: "Payload Objects (Spaceships and Satellites)",
                    data: data1,
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)',
                        'rgba(255, 99, 132, 0.2)',
                    ],
                    borderColor: [
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                    ],
                    borderWidth: 2
                },
                {
                    label: "Other Objects (Space Debris)",
                    data: data2,
                    backgroundColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)',
                        'rgba(255, 99, 132, 1)',
                    ],
                    borderColor: [
                        'rgba(0, 10, 130, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                        'rgba(200, 99, 132, .7)',
                    ],
                    borderWidth: 2
                }
            ]
        },
        options: {
            responsive: true
        }
        });

        var myLineChart2 = new Chart(ctx2, {
            type: 'line',
            data: {
                labels: ["1960", "1970", "1980", "1990", "2000", "2010", "2020"],
                datasets: [
                    {
                        label: "Payload Objects (Spaceships and Satellites)",
                        data: data1,
                        backgroundColor: [
                            'rgba(105, 0, 132, .2)',
                        ],
                        borderColor: [
                            'rgba(200, 99, 132, .7)',
                        ],
                        borderWidth: 2
                    },
                    {
                        label: "Other Objects (Space Debris)",
                        data: data2,
                        backgroundColor: [
                            'rgba(0, 137, 132, .2)',
                        ],
                        borderColor: [
                            'rgba(0, 10, 130, .7)',
                        ],
                        borderWidth: 2
                    }
                ]
            },
            options: {
                responsive: true
            }
        });
    </script>
    <script>
        let mybutton = document.getElementById("topBtn");
        window.onscroll = function() {scrollFunction()};

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
</html>

simulation/templates/simulation/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">
        <title>Simulation - EAW</title>
    </head>
    <style>
        a,
        a:focus,
        a:hover {
        color: #fff;
        }

        .btn-secondary,
        .btn-secondary:hover,
        .btn-secondary:focus {
        color: #333;
        text-shadow: none;
        background-color: #fff;
        border: .05rem solid #fff;
        }

        html,
        body {
        height: 100%;
        background-color: #333;
        }

        body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-pack: center;
        -webkit-box-pack: center;
        justify-content: center;
        color: #fff;
        text-shadow: 0 .05rem .1rem rgba(0, 0, 0, .5);
        box-shadow: inset 0 0 5rem rgba(0, 0, 0, .5);
        }

        .cover-container {
        max-width: 42em;
        }

        .masthead {
        margin-bottom: 2rem;
        }

        .masthead-brand {
        margin-bottom: 0;
        }

        .nav-masthead .nav-link {
        padding: .25rem 0;
        font-weight: 700;
        color: rgba(255, 255, 255, .5);
        background-color: transparent;
        border-bottom: .25rem solid transparent;
        }

        .nav-masthead .nav-link:hover,
        .nav-masthead .nav-link:focus {
        border-bottom-color: rgba(255, 255, 255, .25);
        }

        .nav-masthead .nav-link + .nav-link {
        margin-left: 1rem;
        }

        .nav-masthead .active {
        color: #fff;
        border-bottom-color: #fff;
        }

        @media (min-width: 48em) {
        .masthead-brand {
            float: left;
        }
        .nav-masthead {
            float: right;
        }
        }

        .cover {
        padding: 0 1.5rem;
        }

        .cover .btn-lg {
        padding: .75rem 1.25rem;
        font-weight: 700;
        }
    </style>
    <body class="text-center">
        <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
        <header class="masthead mb-auto">
            <div class="inner">
                <h3 class="masthead-brand">Earth Asteroid Web</h3>
                <nav class="nav nav-masthead justify-content-center">
                    <a class="nav-link" href="{% url 'asteroidInfo:index' %}">Home</a>
                    <a class="nav-link" href="#">Info</a>
                    <a class="nav-link" href="#">Classes</a>
                    <a class="nav-link active" href="#">Simulation</a>
                    <a class="nav-link" href="#">Calculator</a>
                </nav>
            </div>
        </header>

        <main role="main" class="inner cover">
            <h1 class="cover-heading">Simulation</h1>
            <p class="lead">Observe the asteroids that orbit the earth and create a near impenentrable prison.</p>
            <p class="lead">
                <a href="" class="btn btn-lg btn-secondary">Open Simulation</a>
            </p>
        </main>

        <footer class="mastfoot mt-auto">
            <div class="inner">
                <p>Created by Jeff Sunil</p>
            </div>
        </footer>
        </div>
    </body>
</html>